spring.application.name=GGarciaBanco

# ===============================
# DATASOURCE ORACLE 19C
# ===============================

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=GGarciaBanco
spring.datasource.password=password1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configuraci\u00f3n de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# FLYWAY
# ===============================

spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
spring.flyway.baseline-on-migrate=false
# JWT Config
jwt.secret=pFhSxlmsSPAYkxuMGkcbrcS4q3B6LkD2t62QR1a2o7y8EmGfKQCxKe4o6t5
jwt.expiration=86400000 
# ===============================
# EMAIL
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gabrielgarciatoriz@gmail.com
spring.mail.password=ispt ibif xshr plcj 

# Propiedades adicionales de seguridad
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.mime.charset=UTF-8