spring.application.name=GGarciaBanco

# ===============================
# DATASOURCE ORACLE 19C
# ===============================

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=GGarciaBanco
spring.datasource.password=password1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configuraci\u00f3n de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# FLYWAY
# ===============================

spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
spring.flyway.baseline-on-migrate=false
